#dna_array = "AGCTTTTCATT"
dna_array = "GTTACTGGGGGTTCAAGTCATCAGGCACACAGCCAGAGGCGAGTGTTACGGAGAGGACTTCGACGGGGCTTTTCAGTGTCCAGATGATATATTACGTAAAGGCATCGTACCTTTAAATAATCTTTACAGACTTCGGCATCGCCCCGCCCGACAGTCACAACGACTGCTTCCCCCCTCGATCTCCATAGCCCCGTGAGAGTTAACCGTAGTACTTGTCAAGGTAAGGTAATCCGCTTAACGTCGGCCAACTCAATGGTGCTTCGCAAAAGATCCAGCAGGACGTTTAAGCAGTGTCAGGTCCCATTGTGCCCACCCATTTGAGACCTACCGAACACATGGATTATTACATCATGAATCGTGAGTGGAGGGGTAGGGGTAACAATAAGCAGTTAGAAATCCATACTGTGGTCGATAATAAACGGCCCTACACATTCGCCAGGCCCCAGGTCTTCGCCCCCGCAAAACGTTCTATCGGGGACAACGACTAGCCCCTGACTATTCGGTGTCTGATGGTATTATACCTCGGCAATGCTTTGATCTAACCCGCTGGCGGGATACGTTAGCTGTATTAGACGCGCTGTTGGATTATACTCCTGCGGAAAGAATAATCGTTCTCAGCGACGGCGGTAACGGTGACTGGGTTAGCGTGCATCGTTATTATCGAGGGCGCGGTGTCCATTCTTCGGCGTACGAAGTCTCTGCGACTATTCAAATTTAATGATTTTTAAGCGCTAGAACCTGGCAACTATTGCGACGAACTTAACTACAGCCCTTGTGGAGGTGAGGTAGAACATAAGTAGGATCCACTAGGATTACAGGGTTC"

count_A = count_T = count_G = count_C = count_invalid = 0

for x in dna_array:
    if x=="A":
        count_A += 1
    elif x=="T":
        count_T += 1
    elif x=="G":
        count_G += 1
    elif x=="C":
        count_C += 1
    else:
        count_invalid += 1

print "Solution:1"
print "A: %s, T: %s, G: %s, C: %s" % (count_A, count_T, count_G, count_C)
print "invalid characters: %s\n" % (count_invalid)

print "Solution-2:"
nucleotideDictionary = {}
for i in dna_array:
    if i in nucleotideDictionary:
        nucleotideDictionary[i] += 1
    else:
        nucleotideDictionary[i] = 1

print nucleotideDictionary
print "\n"

j = 1
for n in nucleotideDictionary:
    print "%s. count of %s : %s \n" % (j, n,nucleotideDictionary[n])
    j += 1